const products=[
{name:'NordVPN',cat:'VPN',price:4000,icon:'N',desc:'Authorized VPN subscription/service for secure and private internet use.',opts:['Basic — ₦4,000','High — ₦7,500']},
{name:'ExpressVPN',cat:'VPN',price:4000,icon:'E',desc:'ExpressVPN option for compatible devices and secure browsing.',opts:['PC — ₦4,000','Phone — ₦4,500']},
{name:'Proton VPN',cat:'VPN',price:3500,icon:'P',desc:'Authorized Proton VPN service for privacy and secure browsing.',opts:['Standard — ₦3,500','Premium — ₦6,000']},
{name:'Instagram Services',cat:'Social Media',price:3500,icon:'◎',desc:'Legitimate Instagram management and marketing packages.',opts:['Starter — ₦3,500','Growth — ₦5,200','Premium — ₦7,200']},
{name:'TikTok Services',cat:'Social Media',price:4270,icon:'♪',desc:'Legitimate TikTok management and marketing packages.',opts:['Starter — ₦4,270','Growth — ₦5,570','Premium — ₦7,320']},
{name:'Google Voice Services',cat:'Other',price:8000,icon:'G',desc:'Legitimate Google Voice setup and support services.',opts:['Contact support for availability']},
{name:'Facebook Page Services',cat:'Social Media',price:4300,icon:'f',desc:'Authorized services for Facebook Page owners and legitimate projects.',opts:['Setup / management — contact support']},
{name:'AI Video Call Tools',cat:'AI Tools',price:0,icon:'✦',desc:'AI-assisted video-call and communication tools for educational purposes.',opts:['Contact for current pricing']}];
let cat='All',cur;const grid=document.getElementById('grid'),search=document.getElementById('search'),filters=document.getElementById('filters');const money=n=>n?'₦'+n.toLocaleString('en-NG'):'Contact for price';
function filtersDraw(){filters.innerHTML=['All','VPN','Social Media','AI Tools','Other'].map(x=>`<button class="filter ${x===cat?'active':''}" onclick="setCat('${x}')">${x}</button>`).join('')};function setCat(x){cat=x;filtersDraw();draw()};function draw(){let q=search.value.toLowerCase(),list=products.filter(p=>(cat==='All'||p.cat===cat)&&(p.name+' '+p.desc).toLowerCase().includes(q));grid.innerHTML=list.map((p,i)=>`<article class="card"><div class="ico">${p.icon}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="card-bottom"><span class="price">${money(p.price)}</span><button class="view" onclick="openProduct(${products.indexOf(p)})">VIEW →</button></div></article>`).join('')||'<p>No services found.</p>'};function openProduct(i){cur=products[i];mi.textContent=cur.icon;mt.textContent=cur.name;md.textContent=cur.desc;mp.textContent=money(cur.price);mo.innerHTML=cur.opts.map(x=>`<div class="option">${x}</div>`).join('');modal.classList.add('open')};function closeModal(){modal.classList.remove('open')};function buy(){closeModal();toast(cur.name+' selected. Continue to checkout.');location.hash='wallet'}function toast(x){let t=document.getElementById('toast');t.textContent=x;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2500)}function amt(n){amount.value=n}function fund(){let n=Number(amount.value.replace(/[^0-9]/g,''));if(n<1000)return toast('Minimum wallet funding is ₦1,000.');toast('Payment successful — ₦'+n.toLocaleString('en-NG')+' added to your demo wallet.')}search.oninput=draw;filtersDraw();draw();
